### ISSUE TITLE
Publish to RubyGems

### ISSUE THREAD

**Issue by zzeni** [faradayio/hangar#20]
Hi, can you please push the last version to RubyGems, because the current one still uses **FactoryGirl**

Stacktrace:

```
4: from /<PATH>/gems/2.5.0/gems/hangar-0.1.2/config/routes.rb:3:in `block (2 levels) in <main>'
3: from /<PATH>/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:42:in `load_missing_constant'
2: from /<PATH>/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `rescue in load_missing_constant'
1: from /<PATH>/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/<PATH>/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant': uninitialized constant FactoryGirl (NameError)
```

**Comment by rossmeissl** [comment]
@zzeni done!
